Feature: Full permissions flow for frontend
scuhci/sar-frontend pull request #1
Opened 2024-04-13 05:48 UTC by lonalynn

This PR implements all of the frontend-based functionality for users to scrape app permissions.

- Full UI to preview and scroll through app permissions for the first 5 apps is implemented!
- Properly displays permissions based on "Show Permissions" toggle being switched on/off
- 

Additional fixes:
- Bugfixed search button so that it properly passes search term to backend when clicked

2024-04-18 08:47 UTC, akaash11 requested changes

2024-04-18 08:47 UTC, akaash11 commented on .gitignore
We are currently not using Amplify. I don't think these changes are relevant to this PR. But it gitignore so its fine

2024-04-18 19:05 UTC, lonalynn commented on .gitignore
Removed unnecessary parts of gitignore.

2024-04-18 19:05 UTC, lonalynn commented on src/constants/urlConstants.js
Updated URL for deployment.

2024-04-19 00:20 UTC, lonalynn reviewed
Amplify .gitignore removed & URL changed to deployment.

2024-04-19 00:24 UTC, lonalynn commented
TODO from @akaash11's comments during today's meeting:

- Fix "remove this title prop" bug
- Truncate title text w/ellipses
- Info tooltip on "show permissions"

2024-04-19 19:18 UTC, lonalynn commented
Fixed:
- "Remove this title prop" bug
- Info tooltip

TBD but most likely to be backlogged:
- Truncate titlte text with ellipses

2024-04-25 06:27 UTC, akaash11 approved these changes
Permissions tooltip is added.
And the console error is resolved.

2024-04-25 06:40 UTC, merged